weights: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\models\yolov5n\baseline\yolov5\yolov5n.pt
cfg: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\models\yolov5n\baseline\yolov5\models\yolov5n.yaml
data: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\configs\yolov5n-visdrone\visdrone_experiment2.yaml
hyp:
  lr0: 0.001
  lrf: 0.5
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 5.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 0.5
  obj_pw: 1.0
  anchor_t: 4.0
  anchors: 3
  fl_gamma: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.0
  degrees: 0.0
  translate: 0.0
  scale: 0.0
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  label_smoothing: 0.0
  nbs: 64
epochs: 2
batch_size: 8
imgsz: 640
rect: true
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data\hyps
resume_evolve: null
bucket: ''
cache: disk
image_weights: false
device: '0'
multi_scale: true
single_cls: false
optimizer: SGD
sync_bn: false
workers: 2
project: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\scripts\training\visdrone\YOLOv5n\phase1-baseline\experiment-2\logs&results\training
name: exp2_phase2a_quicktest
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 30
freeze:
- 0
save_period: 5
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\scripts\training\visdrone\YOLOv5n\phase1-baseline\experiment-2\logs&results\training\exp2_phase2a_quicktest
