names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor
nc: 10
path: C:\Users\burak\OneDrive\Desktop\Git Repos\drone-obj-detection-lightweight-ai\data\my_dataset\visdrone
test: test/images
train: train/images
val: val/images
