weights: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\models\yolov5n\baseline\yolov5\yolov5n.pt
cfg: ''
data: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\configs\yolov5n-visdrone\visdrone_experiment1.yaml
hyp:
  amp: true
  anchor_t: 4.0
  anchors: 3
  batch_size: 8
  box: 0.05
  box_loss_gain: 0.05
  cache: false
  cls: 0.3
  cls_loss_gain: 0.3
  cls_pw: 1.0
  conf_thres: 0.001
  copy_paste: 0.0
  cos_lr: false
  degrees: 0.0
  deterministic: true
  epochs: 5
  fl_gamma: 0.0
  fliplr: 0.0
  flipud: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.0
  image_weights: false
  img_size: 640
  iou_t: 0.2
  iou_thres: 0.6
  label_smoothing: 0.0
  lr0: 0.01
  lrf: 0.01
  mask_ratio: 4
  max_det: 300
  mixup: 0.0
  momentum: 0.937
  mosaic: 0.0
  multi_scale: false
  name: experiment1-baseline
  obj: 0.7
  obj_loss_gain: 0.7
  obj_pw: 1.0
  optimizer: SGD
  overlap_mask: true
  patience: 300
  perspective: 0.0
  project: yolov5n-visdrone-phase1
  quad: false
  rect: false
  save_period: -1
  scale: 0.0
  shear: 0.0
  single_cls: false
  sync_bn: false
  translate: 0.0
  warmup_bias_lr: 0.1
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
  workers: 8
epochs: 5
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: ..\..\..\..\..\..\models\yolov5n\baseline\yolov5\data\hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 2
project: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\scripts\training\visdrone\YOLOv5n\phase1-baseline\experiment-1\logs&results\training
name: phase1_quicktest_exp1_20250813_014210
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 300
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
cls: 0.3
obj: 0.7
adam: false
val: true
save_dir: C:\Users\burak\OneDrive\Desktop\Git-Repos\drone-obj-detect-lightweight-ai\scripts\training\visdrone\YOLOv5n\phase1-baseline\experiment-1\logs&results\training\phase1_quicktest_exp1_20250813_014210
