epochs: 50
batch_size: 8
optimizer: SGD
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
cls: 0.3
obj: 0.7
box: 0.05
anchor_t: 4.0
cos_lr: false
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
anchors: 3
fl_gamma: 0.0
img_size: 640
rect: false
hsv_h: 0.0
hsv_s: 0.0
hsv_v: 0.0
degrees: 0.0
translate: 0.0
scale: 0.0
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.0
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
label_smoothing: 0.0
workers: 8
cache: false
image_weights: false
multi_scale: false
single_cls: false
overlap_mask: true
mask_ratio: 4
iou_t: 0.2
cls_pw: 1.0
obj_pw: 1.0
box_loss_gain: 0.05
cls_loss_gain: 0.3
obj_loss_gain: 0.7
conf_thres: 0.001
iou_thres: 0.6
max_det: 300
save_period: -1
patience: 300
amp: true
sync_bn: false
quad: false
deterministic: true
project: yolov5n-visdrone-phase1
name: experiment1-baseline
